import Header from "@/components/header";
import { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { ReactNode } from "react";
import "./globals.css";
import { ThemeModeScript } from "flowbite-react";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

type RootLayoutProps = {
  children: ReactNode;
};

export const metadata: Metadata = {
  title: "Cartiers",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ThemeModeScript />
      </head>
      <body className="flex min-h-screen flex-col bg-background font-sans antialiased">
        <Header />
        <main className="container mx-auto flex-1 p-6">{children}</main>
      </body>
    </html>
  );
}
